#服务注册
eureka:
  client:
    service-url:
      default-zone: http://gccx-registry:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: 7000

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          enabled: true
          #将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）
          lower-case-service-id: true
      routes:
        - id: trade-service
          uri: lb://TRADE-SERVICE
          predicates:
            - Path=/trade/**
          filters:
            - StripPrefix=1
        - id: system-service
          uri: lb://SYSTEM-SERVICE
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

# 配置网关忽略验证
gccx:
  gateway:
    skipAuthUrl:
      - /system/public/code
